// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfnbgdpbkylvgnxahwkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbmJnZHBia3lsdmdueGFod2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDEzMzMsImV4cCI6MjA3Mzc3NzMzM30.mnzqeQm4RfJZ85i0LmbdqX9aDZ1uX_yKtEiPDHId4Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});